### PR TITLE
Volume control added

### LINKED ISSUE #1: Volume control
Hey, 

are you planning to add a volume control?

### PR DESCRIPTION
**Pull request by benwiley4000**
Closes #1.

Much harder work than I thought it would be!

### CODE REVIEW

**Comment by steveambielli** [comment]
Can you please provide documentation for the volume bar?

**Comment by benwiley4000** [comment]
Hey @steveambielli - thanks for asking about this! The short answer is that this feature hasn't been released yet. I know it's been more than a year, I had to take a break... but rest assured I am actively working on closing this release in the near future. It's a big one, a lot bigger than just a new volume control.

However I'm expecting to finally get an alpha release of version 2 out soon. In the meantime, if you want to try it out, the [example page for the `next` branch](https://github.com/benwiley4000/react-responsive-audio-player/blob/next/example.html#L234) uses the volume control. Note that the final look might be a bit different. I don't have documentation yet... I want to finalize more details before I do that.

If you want to build and run the `next` branch example page locally, it's pretty easy:

1. Clone the repo and `git checkout next`
2. `npm install`
3. `npm run dev` - this will automatically start a live reloading dev server and open the example page in a browser

**Comment by steveambielli** [comment]
Thanks for the fast response! You're awesome! And thanks for the information. I'm so happy to hear it will be available in the near future. :)

**Comment by benwiley4000** [comment]
@steveambielli yep, thanks for being excited to try it! I'll ping you when an alpha release is ready to try.

**Pull request merged**
